In [1]:
import numpy as np 

In [2]:
arr = np.array([1, 2, 3, 4, 5])
result = []

# Using a loop to square each element (slow)
for num in arr:
    result.append(num ** 2)

print(result) # Output: [1, 4, 9, 16, 25]

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]


In [3]:
# Vectorization 
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2 # Vectoprized Operation
print(result)   # Output: [1 4 9 16 25]

[ 1  4  9 16 25]


In [4]:
# Broadcasting (Scaling the array withjout using extra memory)
arr = np.array([1, 2, 3, 4, 5])
result = arr + 10
print(result) # Output: [11 12 13 14 15]

[11 12 13 14 15]


In [ ]:
# Broadcating with arrays of different sizes
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

result = arr1 + arr2 # Element-Wise addition
print(result)   # Output: [11 22 33]

[11 22 33]


In [7]:
# Broadcasting in a 2D Array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])

result = arr1 + arr2  # Broadcasting arr2 across arr1 
print(result)

#  Output:
# [[2 4 6]
#  [5 7 9]]

[[2 4 6]
 [5 7 9]]


In [8]:
# Applying Broadcasting to Real World Scenario

data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating Mean and Standard Division for each feature (column)
mean = data.mean(axis = 0)
std = data.std(axis = 0)

# Normalizing the data using Broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
