In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 25])

In [3]:
# Compute the mean(Average) of an array
print(np.mean(arr))

6.666666666666667


In [4]:
# Compute the minimum value of an array
print(np.min(arr))

1


In [5]:
# Compute the maximum value of an array
print(np.max(arr))

25


In [6]:
# Compute the Standard Deviation of an array 
print(np.std(arr))

8.29993306532582


In [7]:
# Compute the variance of an array 
print(np.var(arr))

68.88888888888889


In [8]:
# Compute the Sum of all elements in an array
print(np.sum(arr))

40


In [9]:
# Compute the product of all elements in an array/
print(np.prod(arr))

3000


In [10]:
# Compute the median of an array
print(np.median(arr))

3.5


In [11]:
# Compute the Percentile of an array
print(np.percentile(arr, 60))

4.0


In [12]:
# Return the index of the minumum value in an array
print(np.argmin(arr))

0


In [13]:
# Return the index of the maximum value in in array
print(np.argmax(arr))

5


In [14]:
# Compute the correlation coefficiant matrix of two arrays
print(np.corrcoef(arr))

1.0


In [15]:
# Find the unique elements of an array
print(np.unique(arr))

[ 1  2  3  4  5 25]


In [16]:
# Compute the cumulative sum of an array
print(np.cumsum(arr))

[ 1  3  6 10 15 40]


In [17]:
# Compute the n-th difference of an array
print(np.diff(arr))

[ 1  1  1  1 20]


In [18]:
# Create an array with evenly spaced number over a specified interval
print(np.linspace(0, 10, 5))    # 5 numbers from 1 to 10 

[ 0.   2.5  5.   7.5 10. ]


In [19]:
# Compute the natural logarithm of an array
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 3.21887582]


In [20]:
# Compute the exponential value of an array
print(np.exp(arr))

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 7.20048993e+10]
