In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [4]:
arr.astype('float64')

array([1., 2., 3., 4., 5.])

In [5]:
arr2 = np.array([23, 4, 4, 60], dtype='float64')
arr2

array([23.,  4.,  4., 60.])

In [6]:
# DOWNCASTING TO SAVE SYSTEM MEMORY

arr_large = np.array([1000000, 2000000, 3000000], dtype='int64')
arr_small = arr_large.astype('int32')
print(arr_large)
print(arr_small.dtype)

[1000000 2000000 3000000]
int32


In [7]:
# MEMORY USAGE EX:

arr_int64 = np.array([1, 2, 3, 4], dtype='int64')
arr_int32 = np.array([1, 2, 3, 4], dtype='int32')

print(arr_int64.nbytes)  # 32 Bytes
print(arr_int32.nbytes)  # 16 Bytes

32
16


In [12]:
# OBJECT DATA TYPE (NOT RECOMMENDED)

arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype='object')
print(arr)

[{'a': 1} list([1, 2, 3]) 'hello']
